language: csharp
mono: none
dotnet: 3.0.1
solution: Charon.sln
install:
    - dotnet restore Charon.sln
script:
    - dotnet build Charon.sln -c Release
    - mv ./Charon/bin/Release/Charon.*.nupkg ./
deploy:
    skip_cleanup: true
    provider: script
    script: dotnet nuget push Charon/bin/Release/Charon.*.nupkg -k $ApiKey -s https://api.nuget.org/v3/index.json
    on:
        branch: master