language: csharp
solution: Charon.sln
install:
    - nuget restore Charon.sln
script:
    - xbuild Charon.sln -c Release
    - mv ./Charon/bin/Release/netstandard2.0/Charon.dll ./
deploy:
    skip_cleanup: true
    provider: script
    script: nuget pack Charon.nuspec && nuget push Charon.*.nupkg -Verbosity detailed -ApiKey $ApiKey -Source $Source
    on:
        branch: master