language: csharp
mono: none
dotnet: 3.0.1
solution: Charon.sln
install:
    - dotnet restore Charon.sln
script:
    - dotnet build Charon.sln -c Release
    - mv ./Charon/bin/Release/Charon.*.nupkg ./
deploy:
    skip_cleanup: true
    provider: script
    script: dotnet push Charon.*.nupkg -Verbosity detailed -ApiKey $ApiKey -Source $Source
    on:
        branch: master